#!/bin/bash
# ---
# session: "00062"
# type: "script"
# status: "active"
# created: "2025-08-28"
# title: "00062-yaml-compliance-check.sh"
# purpose: "Monitor YAML frontmatter coverage across the project"
# language: "bash"
# category: "yaml"
# topics: ["yaml"]
# priority: "P2"
# domain: "core"
# ---
# YAML Compliance Checker - Session 00062
# Purpose: Monitor YAML frontmatter coverage across the project

echo "📊 YAML Compliance Report"
echo "========================="
echo ""
echo "Generated: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""

# Count total markdown files
TOTAL=$(find . -name "*.md" -type f 2>/dev/null | wc -l)

# Count files with YAML (check for --- at beginning)
WITH_YAML=$(find . -name "*.md" -type f -exec sh -c 'head -1 "$1" 2>/dev/null | grep -q "^---$" && echo "$1"' _ {} \; 2>/dev/null | wc -l)

# Calculate percentage
if [ "$TOTAL" -eq 0 ]; then
    PERCENT="0.0"
else
    PERCENT=$(echo "scale=1; $WITH_YAML * 100 / $TOTAL" | bc)
fi

echo "📈 Overall Coverage: $WITH_YAML/$TOTAL files ($PERCENT%)"
echo ""

# Check specific categories
echo "📂 Category Breakdown:"
echo "----------------------"

# Session logs
LOGS_TOTAL=$(ls archive/sessions/SESSION-*-LOG.md 2>/dev/null | wc -l)
if [ "$LOGS_TOTAL" -gt 0 ]; then
    LOGS_YAML=$(ls archive/sessions/SESSION-*-LOG.md 2>/dev/null | xargs -I {} sh -c 'head -1 "{}" 2>/dev/null | grep -q "^---$" && echo 1' | wc -l)
    LOGS_PERCENT=$(echo "scale=1; $LOGS_YAML * 100 / $LOGS_TOTAL" | bc)
    echo "  📝 Session Logs: $LOGS_YAML/$LOGS_TOTAL ($LOGS_PERCENT%)"
else
    echo "  📝 Session Logs: 0/0 (N/A)"
fi

# Handoffs
HANDOFF_TOTAL=$(ls archive/sessions/*-HANDOFF.md 2>/dev/null | wc -l)
if [ "$HANDOFF_TOTAL" -gt 0 ]; then
    HANDOFF_YAML=$(ls archive/sessions/*-HANDOFF.md 2>/dev/null | xargs -I {} sh -c 'head -1 "{}" 2>/dev/null | grep -q "^---$" && echo 1' | wc -l)
    HANDOFF_PERCENT=$(echo "scale=1; $HANDOFF_YAML * 100 / $HANDOFF_TOTAL" | bc)
    echo "  🤝 Handoffs: $HANDOFF_YAML/$HANDOFF_TOTAL ($HANDOFF_PERCENT%)"
else
    echo "  🤝 Handoffs: 0/0 (N/A)"
fi

# Recent deliverables (files starting with 00XXX)
RECENT_TOTAL=$(ls 00[0-9][0-9][0-9]-*.md 2>/dev/null | wc -l)
if [ "$RECENT_TOTAL" -gt 0 ]; then
    RECENT_YAML=$(ls 00[0-9][0-9][0-9]-*.md 2>/dev/null | xargs -I {} sh -c 'head -1 "{}" 2>/dev/null | grep -q "^---$" && echo 1' | wc -l)
    RECENT_PERCENT=$(echo "scale=1; $RECENT_YAML * 100 / $RECENT_TOTAL" | bc)
    echo "  📦 Session Deliverables: $RECENT_YAML/$RECENT_TOTAL ($RECENT_PERCENT%)"
else
    echo "  📦 Session Deliverables: 0/0 (N/A)"
fi

# Requirements domain
REQ_TOTAL=$(find requirements -name "*.md" -type f 2>/dev/null | wc -l)
if [ "$REQ_TOTAL" -gt 0 ]; then
    REQ_YAML=$(find requirements -name "*.md" -type f -exec sh -c 'head -1 "$1" 2>/dev/null | grep -q "^---$" && echo "$1"' _ {} \; 2>/dev/null | wc -l)
    REQ_PERCENT=$(echo "scale=1; $REQ_YAML * 100 / $REQ_TOTAL" | bc)
    echo "  📋 Requirements Domain: $REQ_YAML/$REQ_TOTAL ($REQ_PERCENT%)"
else
    echo "  📋 Requirements Domain: 0/0 (N/A)"
fi

# Reality domain
REALITY_TOTAL=$(find reality -name "*.md" -type f 2>/dev/null | wc -l)
if [ "$REALITY_TOTAL" -gt 0 ]; then
    REALITY_YAML=$(find reality -name "*.md" -type f -exec sh -c 'head -1 "$1" 2>/dev/null | grep -q "^---$" && echo "$1"' _ {} \; 2>/dev/null | wc -l)
    REALITY_PERCENT=$(echo "scale=1; $REALITY_YAML * 100 / $REALITY_TOTAL" | bc)
    echo "  🔍 Reality Domain: $REALITY_YAML/$REALITY_TOTAL ($REALITY_PERCENT%)"
else
    echo "  🔍 Reality Domain: 0/0 (N/A)"
fi

# Files modified in last 7 days without YAML
echo ""
echo "⚠️  Recently Modified Files Missing YAML (last 7 days):"
echo "-------------------------------------------------------"
RECENT_NO_YAML=$(find . -name "*.md" -mtime -7 -type f -exec sh -c 'head -1 "$1" 2>/dev/null | grep -q "^---$" || echo "$1"' _ {} \; 2>/dev/null | head -10)
if [ -z "$RECENT_NO_YAML" ]; then
    echo "  ✅ All recently modified files have YAML!"
else
    echo "$RECENT_NO_YAML" | while read -r file; do
        echo "  - $file"
    done
fi

# Coverage targets
echo ""
echo "🎯 Coverage Targets:"
echo "-------------------"
echo "  Current:  $PERCENT%"
echo "  Target:   >10% (Session 62)"
echo "  Goal:     >50% (Long-term)"
echo "  Ideal:    100% (Full visibility)"

# Health assessment
echo ""
echo "💊 Health Assessment:"
echo "--------------------"
if (( $(echo "$PERCENT > 10" | bc -l) )); then
    echo "  ✅ GOOD: Coverage above 10% target"
elif (( $(echo "$PERCENT > 5" | bc -l) )); then
    echo "  ⚠️  FAIR: Coverage approaching target"
else
    echo "  ❌ POOR: Coverage below 5%"
fi

if (( $(echo "$LOGS_PERCENT > 80" | bc -l) )); then
    echo "  ✅ Session logs well-documented"
elif (( $(echo "$LOGS_PERCENT > 50" | bc -l) )); then
    echo "  ⚠️  Session logs need attention"
else
    echo "  ❌ Session logs poorly documented"
fi

echo ""
echo "---"
echo "Generated by Session 00062 YAML Compliance Checker"