#!/bin/bash
# Enhanced Session Start with MCP Integration
# Session 136 - Adds Sequential Thinking planning phase

set -e

SESSION_ID=${1:-"00136"}
echo "🚀 Starting Enhanced Session $SESSION_ID with MCP Integration"
echo "============================================================"

# Run standard session start
echo "📋 Running standard session initialization..."
./scripts/00028-session-start.sh $SESSION_ID

# Add Sequential Thinking planning phase
echo ""
echo "🧠 Planning Session Work with Sequential Thinking..."
echo "------------------------------------------------------------"

python3 << 'PYTHON_SCRIPT'
import json
import sys
from datetime import datetime

def plan_session_with_thinking(session_id):
    """Use Sequential Thinking to plan session work"""
    
    # This is a mock implementation - in real use, would call MCP
    print(f"Planning Session {session_id} implementation approach...")
    
    # Read any handoff document
    import os
    handoff_path = f"archive/sessions/SESSION-{session_id}-HANDOFF.md"
    context = ""
    if os.path.exists(handoff_path):
        with open(handoff_path, 'r') as f:
            context = f.read()[:500]  # First 500 chars for context
    
    # Generate structured plan (mock for now)
    plan = f"""---
session: "{session_id}"
type: "session-plan"
created: "{datetime.now().isoformat()}"
generated_by: "Sequential Thinking MCP"
---

# Session {session_id} Implementation Plan

## Context Analysis
Based on previous session handoff and system state.

## Recommended Approach
1. Start with highest priority items from handoff
2. Use test-first development approach
3. Validate with orchestrator after each feature
4. Create automated PR when validation passes

## Implementation Order
1. Review Session 134-135 Q&A for Guardian/Friends priorities
2. Implement Guardian empty insert fix (highest impact)
3. Add Friends real-time if time permits
4. Document all changes

## Risk Mitigation
- Test each change before moving forward
- Run orchestrator health checks frequently
- Watch for 95% syndrome patterns

---
Generated by MCP Enhanced Workflow
"""
    
    # Save plan
    plan_path = f"archive/sessions/SESSION-{session_id}-PLAN.md"
    with open(plan_path, 'w') as f:
        f.write(plan)
    
    print(f"✅ Session plan saved to: {plan_path}")
    return plan

# Execute planning
plan = plan_session_with_thinking('SESSION_ID')
PYTHON_SCRIPT

echo ""
echo "✅ Enhanced session initialization complete!"
echo "📚 Review your session plan: archive/sessions/SESSION-$SESSION_ID-PLAN.md"
echo "============================================================"